### ISSUE TITLE
CSDN Focus: 关于文章作者名片的问题

### ISSUE THREAD

**Issue by TarsChiu** [Germxu/Scripts-for-TamperMonkey#1]
# 可以考虑不要净化一下内容吗
---
### 最近的热门文章

这些在我们找资料的过程中可以起到积极的作用。
希望您可以在脚本中添加一些注释，可以让我们自行修改，达到各自想要的样子。
另外，新年快乐噢😁~

**Comment by Germxu** [comment]
我后面考虑一下左侧名片栏的展现方式和配置项, 因为CSDN脚本本来只是纯CSS重置, 所以我还是尽量少使用脚本来修改内容, 
谢谢你的建议, 新年快乐(*^▽^*)

**Comment by Germxu** [comment]
已经更新哦, 还是以CSS修改, 探索一下吧, 希望能满意\(^o^)/~

**Comment by TarsChiu** [comment]
这么修改太棒了！既不影响文章阅读，又可以保证信息的完整性。看看大家喜欢这种阅读方式不。(๑❛ᴗ❛๑)send-------- 原始邮件 --------发件人： Germxu <notifications@github.com>日期： 2021年2月18日周四 晚上10:53收件人： Germxu/Scripts-for-TamperMonkey <Scripts-for-TamperMonkey@noreply.github.com>抄送： TarsChiu <2059192947@qq.com>, Author <author@noreply.github.com>主    题： Re: [Germxu/Scripts-for-TamperMonkey] 关于文章作者名片的问题 (#1)

我后面考虑一下左侧名片栏的展现方式和配置项, 因为CSDN脚本本来只是纯CSS重置, 所以我还是尽量少使用脚本来修改内容,

谢谢你的建议, 新年快乐(^▽^)

**Comment by TarsChiu** [comment]
这么修改太棒了！既不影响文章阅读，又可以保证信息的完整性。看看大家喜欢这种阅读方式不。😊
支持你哟！🤞

**Comment by Germxu** [comment]
哈哈, 有人喜欢就开心^_^
最近太忙了, 还有俩更有意思的脚本都没时间做了 ┭┮﹏┭┮

**Comment by TarsChiu** [comment]
(｡･∀･)ﾉﾞ嗨
我看到你的更新了，非常nice的(๑•̀ㅂ•́)و✧。与此同时，我有个小小的建议，
作者信息那里可以在往下滑动时与文章同步滚动吗？
现在的感觉比较生硬
或者让左侧的作者信息可以单独滚动
你觉得怎么样？

**Comment by Germxu** [comment]
那是CSDN自己做的, 我这边只是左移了, 其实一直都这样的, 我看一下怎么处理更好吧, 还是让用户自己滚动吧
其实最下面推荐的提示标签更头疼, 没法CSS添加固定的提示标签, 看样子只能写js来处理了

**Comment by Germxu** [comment]
那是CSDN自己做的, 我这边只是左移了, 其实一直都这样的, 我看一下怎么处理更好吧, 还是让用户自己滚动吧
其实最下面推荐的提示标签更头疼, 没法CSS添加固定的提示标签, 看样子只能写js来处理了

**Comment by Germxu** [comment]
> (｡･∀･)ﾉﾞ嗨
> 我看到你的更新了，非常nice的(๑•̀ㅂ•́)و✧。与此同时，我有个小小的建议，
> 作者信息那里可以在往下滑动时与文章同步滚动吗？
> 现在的感觉比较生硬
> 或者让左侧的作者信息可以单独滚动
> 你觉得怎么样？

已经更新了, CSS限制目前只能这样修改, 有些生硬

**Comment by TarsChiu** [comment]
其实我觉得你写的是我在众多的CSDN净化脚本中做的最好的一个，但是用的人有点点少。您希望我向我的朋友们推荐一下你的作品吗？ ฅ( ̳• ◡ • ̳)ฅ

**Comment by TarsChiu** [comment]
可以考虑一下这个吗？

`#FinnTop{width:36px;height:36px;position:fixed;left:60%;margin-left:520px;bottom:30px;z-index:999;cursor:pointer;background:#fff;border-radius:50%;box-shadow:0 0 20px #75757545;}`

感觉这样的TOP键位置舒服一些，但是窗口缩小就看不见了😂

**Comment by TarsChiu** [comment]
> 那是CSDN自己做的, 我这边只是左移了, 其实一直都这样的, 我看一下怎么处理更好吧, 还是让用户自己滚动吧
> 其实最下面推荐的提示标签更头疼, 没法CSS添加固定的提示标签, 看样子只能写js来处理了

换个思路，把文字变成一个半圆，这样用户就知道这里藏了东西了

推荐阅读的话，其实用户很自然就发现了，在简介里介绍一下就可以了

用户其实最需要的是简介干净但又不丢失信息。

希望我的建议对你有帮助啦😁

加油！一直支持你的！O(∩_∩)O

**Comment by TarsChiu** [comment]
> 那是CSDN自己做的, 我这边只是左移了, 其实一直都这样的, 我看一下怎么处理更好吧, 还是让用户自己滚动吧
> 其实最下面推荐的提示标签更头疼, 没法CSS添加固定的提示标签, 看样子只能写js来处理了

换个思路，把文字变成一个半圆，这样用户就知道这里藏了东西了

推荐阅读的话，其实用户很自然就发现了，在脚本简介里简单介绍一下就可以了

用户其实最需要的是简介干净但又不丢失信息。

希望我的建议对你有帮助啦😁

加油！一直支持你的！O(∩_∩)O

**Comment by Germxu** [comment]
> 可以考虑一下这个吗？
> 
> `#FinnTop{width:36px;height:36px;position:fixed;left:60%;margin-left:520px;bottom:30px;z-index:999;cursor:pointer;background:#fff;border-radius:50%;box-shadow:0 0 20px #75757545;}`
> 
> 感觉这样的TOP键位置舒服一些，但是窗口缩小就看不见了😂

功能优先吧, 宽屏幕窄屏幕的按钮远离内容或者看不到都是很不舒服的

**Comment by Germxu** [comment]
> 其实我觉得你写的是我在众多的CSDN净化脚本中做的最好的一个，但是用的人有点点少。您希望我向我的朋友们推荐一下你的作品吗？ ฅ( ̳• ◡ • ̳)ฅ

当然可以啊, 因为脚本商店有些规则不是很合理, 新脚本也很难被发现, 每次我发现都是更新后才会被搜索结果推荐到首页, 然后就基本没人安装了, 有点伤心😞
