### ISSUE TITLE
大大，提几个建议

### ISSUE THREAD

**Issue by ztf111** [Germxu/Scripts-for-TamperMonkey#13]
大大，我觉得左侧边栏只需要目录就够了，其他的都可以屏蔽掉；
另外，要是能有个一键复制代码的功能就更好了；
页面最上面搜索框的白色背景可以改成透明，整体更协调；
左侧边的红色按钮可以改成小小的箭头样式，然后居中，现在这个按钮看起来不是很舒服；
还有，页面的背景要是能够自定义就好了
油猴上有一个脚本叫CSDN去广告沉浸阅读模式，它在美学上做的很好，大大可以看一下它的美学思路

最后，感谢大大做出这么好的脚本

**Comment by TarsChiu** [comment]
我自己拿大大的脚本改了下
符合我自己的审美😂
你可以试试看

// ==UserScript==
// @name         CSDN Focus
// @description  🌚 黑暗模式上线, 一键变天 | CSDN, 脚本之家 无弹窗无广告无任何干扰, 自动展开文章和评论, 外链直达! 隐藏属性等你发现, 不试一下? 😃
// @version      1.6
// @author       Finn
// @namespace    https://github.com/Germxu
// @homepage     https://github.com/Germxu/Scripts-for-TamperMonkey
// @supportURL   https://github.com/Germxu/Scripts-for-TamperMonkey/issues/new
// @run-at       document-start
// @match        blog.csdn.net/*/article/details/*
// @match        *.blog.csdn.net/article/details/*
// @match        www.jb51.net/article/*
//
// @grant        GM_setValue
// @grant        GM_getValue
// @license      MIT
// @compatible   chrome 54+
//
// @note         V1.6 重要更新: 修复了一直以来可能出现的运行不成功和后台加载脚本失败的问题
// @note         V1.5 重要更新: 添加黑暗模式, 一键切换, 优化精简大量静态代码,修复隐性Bug
// ==/UserScript==

(function () {
    'use strict';
    const csdn = `<style> [DarkMode],[darkMode] #darkBtn,[darkMode] img,[darkMode] code.hljs,[darkMode] pre.prettyprint{filter:invert(1) hue-rotate(180deg);transition:all 0.5s}[darkModE] body{background:#ebebeb !important;transition:background 0.7s}#darkBtn{position:fixed;top:8px;left:50px;width:32px;height:32px;z-index:9999;background:gold;cursor:pointer;border-radius:50%;transition:all 0.5s}[darkMode] #darkBtn{background:transparent;box-shadow:-0.5em 0.3em 0 0 gold;left:60px;top:4px}div#darkBtn:before{content:"";width:50px;height:50px;display:block;transform:translate(-10px,-10px)}#darkBtn:after{content:"";width:100px;position:absolute;right:-120px;top:4px;font-size:14px;font-weight:600;transition:all 0.5s;display:none}[darkMode] #darkBtn:after{content:"";right:-110px;top:8px;filter:invert(1) hue-rotate(180deg);font-weight:600;}#darkBtn:hover:after{display:block}#csdn-toolbar .toolbar-advert,#csdn-toolbar .toolbar-container-left,#csdn-toolbar .toolbar-container-right,.toolbar-search-drop-menu.toolbar-search-half,::-webkit-input-placeholder,#placeholder,#blogColumnPayAdvert,.csdn-side-toolbar,#dmp_ad_58,#footerRightAds,.csdn-shop-window-common,.login-mark,.blog-footer-bottom,.template-box,.leftPop,#toolBarBox,.comment-edit-box.d-flex,#passportbox,.opt-box.text-center,.hide-article-box.hide-article-pos.text-center,#rightAside,.hljs-button.signin{display:none !important;color:transparent;visibility:hidden}.toolbar-search.onlySearch{transition:all 0.3s ease;}body #csdn-toolbar{box-shadow:0 2px 10px 0 rgba(0,0,0,.15);position:fixed !important;top:0px;left:0px;width:100%;z-index:1993;}.toolbar-search.onlySearch:focus-within{max-width:1000px !important;width:1000px !important}.d-flex{display:block !important}.main_father{height:auto !important;}main{width:100% !important;box-shadow:0 0 30px #959fa378;margin-bottom:0 !important;}#mainBox{margin:50px auto;width:1000px !important}.comment-list-box{max-height:none !important}#commentPage,.toolbar-container-middle{display:block !important}#article_content{height:auto !important}.comment-list-container{padding:4px 0 !important}.article-header-box{padding-top:18px !important}main .comment-box{padding:0;box-shadow:0 0 10px rgba(0,0,0,0.05);margin:8px 0;}#FinnTop{width:36px;height:36px;color:#ff4d4d;font:600 14px/44px arial;text-align:center;position:fixed;left:60%;margin-left:520px;bottom:30px;z-index:999;cursor:pointer;background:#fff;border-radius:50%;box-shadow:0 0 20px #75757545;}#FinnTop:before{content:"";position:absolute;left:28%;top:36%;color:#ff4d4d;width:14px;height:14px;border-top:2px solid #ff4d4d;border-left:2px solid #ff4d4d;transform:rotate(45deg)}.blog_container_aside{height:calc(100% - 80px);overflow-y:auto;overflow-x:hidden;border:solid #fff;border-width:20px 4px 0 4px;background:#fff;box-sizing:content-box;position:fixed;top:initial !important;left:-307.8px !important;;transition:all 0.35s;box-shadow:2px 0 10px 0 rgba(0,0,0,.15);z-index:99;}.blog_container_aside::-webkit-scrollbar-track{-webkit-box-shadow:inset 0 0 15px rgba(0,0,0,0.13);background-color:#fefefe;}.blog_container_aside::-webkit-scrollbar{width:6px;height:6px;background-color:#eee;}.blog_container_aside::-webkit-scrollbar-thumb{border-radius:6px;background-color:#cecece;}.blog_container_aside:hover{left:0px !important;}.recommend-box.insert-baidu-box{height:79%;overflow:scroll;position:fixed;background:#fff;box-sizing:content-box;transition:all 0.38s;box-shadow:0 -3px 10px 0 rgba(0,0,0,.25);border:10px solid #fff;z-index:1995;top:calc(100% - 7px);left:0;right:0;margin:auto;width:1000px;}.recommend-box.insert-baidu-box:hover{top:29%}.recommend-box.insert-baidu-box::-webkit-scrollbar-thumb{background-color:rgba(153,154,170,0.3);}.recommend-box.insert-baidu-box::-webkit-scrollbar{width:5px;height:100px;}.recommend-item-box{display:none !important;}.recommend-item-box.type_blog{display:block !important;}/*aside.blog_container_aside:before{width:14px;animation:_l 1s ease-in forwards;position:fixed;top:58px;left:0;z-index:999;padding:5px 1px;background:#ff4d4d;text-align:center;color:#fff;content:" "attr(username) " "*/;writing-mode:tb-rl;font-size:12px;line-height:1.4;transition:all 0.35s ***@***.*** _l{from{left:-20px;}to{left:0;}}aside.blog_container_aside:hover::before{width:308px;height:18px;padding:4px 0;writing-mode:rl-tb;font-size:14px;}/*.recommend-box.insert-baidu-box:before{position:fixed;bottom:40px;left:50%;margin-left:510px;padding:4px;background:#ff4d4d;color:#fff;content:"推荐阅读"*/;font-size:13px}</style><div id="darkBtn"></div><div id="FinnTop"></div>`;
    const jb51 = `<style> #main .main-right,#topbar,#footer,.pt10,.lbd,.xgcomm,#header,.lbd_bot,#ewm,.subnav,.art_xg,.tags,#comments{display:none !important;}body #main .main-left{padding:0;width:unset;float:none}body #article{padding:15px 20px 20px;box-shadow:0 0 30px rgb(0 0 0 / 25%)}#ewm+p{font-weight:bold;text-align:center;margin:20px;font-size:24px;}body .syntaxhighlighter .line.alt1,body .syntaxhighlighter .line.alt2{background:#d4dbdc !important}body .syntaxhighlighter div{padding:10px 0px !important}.jb51code{width:960px !important}.jb51code .syntaxhighlighter table{background:#d4dbdc !important}</style>`;
    let h = document.documentElement, _Ds;
    let FinnData = new Proxy(GM_getValue('FinnData', {}), {
        set(target, key, val) {
            key === "dark" && val ? h.setAttribute("darkMode", true) : h.removeAttribute("darkMode");
            Reflect.set(target, key, val);
            GM_setValue('FinnData', FinnData);
            return true;
        }
    })
    if (location.host === "www.jb51.net") { _Ds = jb51; } else {
        _Ds = csdn;
        window.addEventListener("DOMContentLoaded", function () {
            document.querySelector(".blog_container_aside").setAttribute("username", username);
            document.body.addEventListener('click', function (e) {
                let ev = e.target;
                if (ev.nodeName.toLocaleLowerCase() === 'a') {
                    if (ev.host.indexOf("csdn") === -1) {
                        e.stopImmediatePropagation();
                        window.open(ev.href);
                        e.preventDefault();
                    }
                }
            }, true);
            $("#FinnTop").click(function () {
                $("body,html").animate({ scrollTop: 0 }, 300);
            });
            $("#darkBtn").click(function () { FinnData.dark ? FinnData.dark = !1 : FinnData.dark = !0; })
        })
    }
    if (!h) {
        let OB = new MutationObserver(ins);
        OB.observe(document, { childList: true })
    } else {
        ins()
    }
    function ins() {
        h = document.documentElement;
        h.insertAdjacentHTML('afterbegin', _Ds);
        FinnData.dark && h.setAttribute("darkMode", true);
    }
})();

**Comment by ztf111** [comment]
> 我自己拿大大的脚本改了下 符合我自己的审美😂 你可以试试看 // ==UserScript== // @name CSDN Focus // @description 🌚 黑暗模式上线, 一键变天 | CSDN, 脚本之家 无弹窗无广告无任何干扰, 自动展开文章和评论, 外链直达! 隐藏属性等你发现, 不试一下? 😃 // @Version 1.6 // @author Finn // @namespace https://github.com/Germxu // @homepage https://github.com/Germxu/Scripts-for-TamperMonkey // @supportURL https://github.com/Germxu/Scripts-for-TamperMonkey/issues/new // @run-at document-start // @match blog.csdn.net/*/article/details/* // @match *.blog.csdn.net/article/details/* // @match [www.jb51.net/article/*](http://www.jb51.net/article/*) // // @grant GM_setValue // @grant GM_getValue // @license MIT // @compatible chrome 54+ // // @note V1.6 重要更新: 修复了一直以来可能出现的运行不成功和后台加载脚本失败的问题 // @note V1.5 重要更新: 添加黑暗模式, 一键切换, 优化精简大量静态代码,修复隐性Bug // ==/UserScript== (function () { 'use strict'; const csdn = `<style> [DarkMode],[darkMode] #darkBtn,[darkMode] img,[darkMode] code.hljs,[darkMode] pre.prettyprint{filter:invert(1) hue-rotate(180deg);transition:all 0.5s}[darkModE] body{background:#ebebeb !important;transition:background 0.7s}#darkBtn{position:fixed;top:8px;left:50px;width:32px;height:32px;z-index:9999;background:gold;cursor:pointer;border-radius:50%;transition:all 0.5s}[darkMode] #darkBtn{background:transparent;box-shadow:-0.5em 0.3em 0 0 gold;left:60px;top:4px}div#darkBtn:before{content:"";width:50px;height:50px;display:block;transform:translate(-10px,-10px)}#darkBtn:after{content:"";width:100px;position:absolute;right:-120px;top:4px;font-size:14px;font-weight:600;transition:all 0.5s;display:none}[darkMode] #darkBtn:after{content:"";right:-110px;top:8px;filter:invert(1) hue-rotate(180deg);font-weight:600;}#darkBtn:hover:after{display:block}#csdn-toolbar .toolbar-advert,#csdn-toolbar .toolbar-container-left,#csdn-toolbar .toolbar-container-right,.toolbar-search-drop-menu.toolbar-search-half,::-webkit-input-placeholder,#placeholder,#blogColumnPayAdvert,.csdn-side-toolbar,#dmp_ad_58,#footerRightAds,.csdn-shop-window-common,.login-mark,.blog-footer-bottom,.template-box,.leftPop,#toolBarBox,.comment-edit-box.d-flex,#passportbox,.opt-box.text-center,.hide-article-box.hide-article-pos.text-center,#rightAside,.hljs-button.signin{display:none !important;color:transparent;visibility:hidden}.toolbar-search.onlySearch{transition:all 0.3s ease;}body #csdn-toolbar{box-shadow:0 2px 10px 0 rgba(0,0,0,.15);position:fixed !important;top:0px;left:0px;width:100%;z-index:1993;}.toolbar-search.onlySearch:focus-within{max-width:1000px !important;width:1000px !important}.d-flex{display:block !important}.main_father{height:auto !important;}main{width:100% !important;box-shadow:0 0 30px #959fa378;margin-bottom:0 !important;}#mainBox{margin:50px auto;width:1000px !important}.comment-list-box{max-height:none !important}#commentPage,.toolbar-container-middle{display:block !important}#article_content{height:auto !important}.comment-list-container{padding:4px 0 !important}.article-header-box{padding-top:18px !important}main .comment-box{padding:0;box-shadow:0 0 10px rgba(0,0,0,0.05);margin:8px 0;}#FinnTop{width:36px;height:36px;color:#ff4d4d;font:600 14px/44px arial;text-align:center;position:fixed;left:60%;margin-left:520px;bottom:30px;z-index:999;cursor:pointer;background:#fff;border-radius:50%;box-shadow:0 0 20px #75757545;}#FinnTop:before{content:"";position:absolute;left:28%;top:36%;color:#ff4d4d;width:14px;height:14px;border-top:2px solid #ff4d4d;border-left:2px solid #ff4d4d;transform:rotate(45deg)}.blog_container_aside{height:calc(100% - 80px);overflow-y:auto;overflow-x:hidden;border:solid #fff;border-width:20px 4px 0 4px;background:#fff;box-sizing:content-box;position:fixed;top:initial !important;left:-307.8px !important;;transition:all 0.35s;box-shadow:2px 0 10px 0 rgba(0,0,0,.15);z-index:99;}.blog_container_aside::-webkit-scrollbar-track{-webkit-box-shadow:inset 0 0 15px rgba(0,0,0,0.13);background-color:#fefefe;}.blog_container_aside::-webkit-scrollbar{width:6px;height:6px;background-color:#eee;}.blog_container_aside::-webkit-scrollbar-thumb{border-radius:6px;background-color:#cecece;}.blog_container_aside:hover{left:0px !important;}.recommend-box.insert-baidu-box{height:79%;overflow:scroll;position:fixed;background:#fff;box-sizing:content-box;transition:all 0.38s;box-shadow:0 -3px 10px 0 rgba(0,0,0,.25);border:10px solid #fff;z-index:1995;top:calc(100% - 7px);left:0;right:0;margin:auto;width:1000px;}.recommend-box.insert-baidu-box:hover{top:29%}.recommend-box.insert-baidu-box::-webkit-scrollbar-thumb{background-color:rgba(153,154,170,0.3);}.recommend-box.insert-baidu-box::-webkit-scrollbar{width:5px;height:100px;}.recommend-item-box{display:none !important;}.recommend-item-box.type_blog{display:block !important;}/*aside.blog_container_aside:before{width:14px;animation:_l 1s ease-in forwards;position:fixed;top:58px;left:0;z-index:999;padding:5px 1px;background:#ff4d4d;text-align:center;color:#fff;content:" "attr(username) " "*/;writing-mode:tb-rl;font-size:12px;line-height:1.4;transition:all 0.35s ***@***.*** _l{from{left:-20px;}to{left:0;}}aside.blog_container_aside:hover::before{width:308px;height:18px;padding:4px 0;writing-mode:rl-tb;font-size:14px;}/*.recommend-box.insert-baidu-box:before{position:fixed;bottom:40px;left:50%;margin-left:510px;padding:4px;background:#ff4d4d;color:#fff;content:"推荐阅读"*/;font-size:13px}</style><div id="darkBtn"></div><div id="FinnTop"></div>`; const jb51 = `<style> #main .main-right,#topbar,#footer,.pt10,.lbd,.xgcomm,#header,.lbd_bot,#ewm,.subnav,.art_xg,.tags,#comments{display:none !important;}body #main .main-left{padding:0;width:unset;float:none}body #article{padding:15px 20px 20px;box-shadow:0 0 30px rgb(0 0 0 / 25%)}#ewm+p{font-weight:bold;text-align:center;margin:20px;font-size:24px;}body .syntaxhighlighter .line.alt1,body .syntaxhighlighter .line.alt2{background:#d4dbdc !important}body .syntaxhighlighter div{padding:10px 0px !important}.jb51code{width:960px !important}.jb51code .syntaxhighlighter table{background:#d4dbdc !important}</style>`; let h = document.documentElement, _Ds; let FinnData = new Proxy(GM_getValue('FinnData', {}), { set(target, key, val) { key === "dark" && val ? h.setAttribute("darkMode", true) : h.removeAttribute("darkMode"); Reflect.set(target, key, val); GM_setValue('FinnData', FinnData); return true; } }) if (location.host === "[www.jb51.net](http://www.jb51.net)") { _Ds = jb51; } else { _Ds = csdn; window.addEventListener("DOMContentLoaded", function () { document.querySelector(".blog_container_aside").setAttribute("username", username); document.body.addEventListener('click', function (e) { let ev = e.target; if (ev.nodeName.toLocaleLowerCase() === 'a') { if (ev.host.indexOf("csdn") === -1) { e.stopImmediatePropagation(); window.open(ev.href); e.preventDefault(); } } }, true); $("#FinnTop").click(function () { $("body,html").animate({ scrollTop: 0 }, 300); }); $("#darkBtn").click(function () { FinnData.dark ? FinnData.dark = !1 : FinnData.dark = !0; }) }) } if (!h) { let OB = new MutationObserver(ins); OB.observe(document, { childList: true }) } else { ins() } function ins() { h = document.documentElement; h.insertAdjacentHTML('afterbegin', _Ds); FinnData.dark && h.setAttribute("darkMode", true); } })();

666

**Comment by Germxu** [comment]
你按上面的看一下吧, 这里你提的几个点不是很同意, 这里还有我的一些打算: 
1. 目录不一定存在, 我没有写很多js的代码去处理已有功能, 侧边栏直接保留, 
2. 搜索框你说的应该是搜索结果的推荐, 我稍后看一下有没有更好的显示效果
3. 背景也是文章本身的, 我没有处理, 也不会添加外源, 我认为这是无意义的东西, 只是在黑暗模式下防止突兀去掉了背景(我的脚本已经这么优雅了 ( •̀ ω •́ )✧
4. 红色的按钮其实是为了更多用户能有意触发到的引导, 我本来是没有添加的,后面可以再做小一点 (用户多了总是很难保持纯粹😅
5. 除了CSS折叠了, 我的代码没有过百行, 我不强求添加太多功能🤨
6. 后面我会处理一下打印/保存PDF 的一些样式问题, 以及其他的细节问题,包括你提到的可优化细节
### 谢谢建议, 努力做更好😆

**Comment by ztf111** [comment]
大大，搜索框是这个东西，就是这个白色长条，我想除了这个黄色圆圈和这个搜索框，剩下的白色背景能不能变透明，文章向下滚动时，最上面一直顶着个白色长条，看着不是很舒服



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月18日(星期五) 下午4:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Germxu/Scripts-for-TamperMonkey] 大大，提几个建议 (#13)





 
你按上面的看一下吧, 这里你提的几个点不是很同意, 这里还有我的一些打算:
  
目录不一定存在, 我没有写很多js的代码去处理已有功能, 侧边栏直接保留,
 
搜索框你说的应该是搜索结果的推荐, 我稍后看一下有没有更好的显示效果
 
背景也是文章本身的, 我没有处理, 也不会添加外源, 我认为这是无意义的东西, 只是在黑暗模式下防止突兀去掉了背景(我的脚本已经这么优雅了 ( •̀ ω •́ )✧
 
红色的按钮其实是为了更多用户能有意触发到的引导, 我本来是没有添加的,后面可以再做小一点 (用户多了总是很难保持纯粹😅
 
除了CSS折叠了, 我的代码没有过百行, 我不强求添加太多功能🤨
 
后面我会处理一下打印/保存PDF 的一些样式问题, 以及其他的细节问题,包括你提到的可优化细节
  
谢谢建议, 努力做更好😆

**Comment by Germxu** [comment]
> > 我自己拿大大的脚本改了下 符合我自己的审美😂 你可以试试看 // ==UserScript== // @name CSDN Focus // @description 🌚 黑暗模式上线, 一键变天 | CSDN, 脚本之家 无弹窗无广告无任何干扰, 自动展开文章和评论, 外链直达! 隐藏属性等你发现, 不试一下? 😃 // @Version 1.6 // @author Finn // @namespace https://github.com/Germxu // @homepage https://github.com/Germxu/Scripts-for-TamperMonkey // @supportURL https://github.com/Germxu/Scripts-for-TamperMonkey/issues/new // @run-at document-start // @match blog.csdn.net/_/article/details/_ // @match _.blog.csdn.net/article/details/_ // @match [www.jb51.net/article/*](http://www.jb51.net/article/*) // // @grant GM_setValue // @grant GM_getValue // @license MIT // @compatible chrome 54+ // // @note V1.6 重要更新: 修复了一直以来可能出现的运行不成功和后台加载脚本失败的问题 // @note V1.5 重要更新: 添加黑暗模式, 一键切换, 优化精简大量静态代码,修复隐性Bug // ==/UserScript== (function () { 'use strict'; const csdn = `<style> [DarkMode],[darkMode] #darkBtn,[darkMode] img,[darkMode] code.hljs,[darkMode] pre.prettyprint{filter:invert(1) hue-rotate(180deg);transition:all 0.5s}[darkModE] body{background:#ebebeb !important;transition:background 0.7s}#darkBtn{position:fixed;top:8px;left:50px;width:32px;height:32px;z-index:9999;background:gold;cursor:pointer;border-radius:50%;transition:all 0.5s}[darkMode] #darkBtn{background:transparent;box-shadow:-0.5em 0.3em 0 0 gold;left:60px;top:4px}div#darkBtn:before{content:"";width:50px;height:50px;display:block;transform:translate(-10px,-10px)}#darkBtn:after{content:"";width:100px;position:absolute;right:-120px;top:4px;font-size:14px;font-weight:600;transition:all 0.5s;display:none}[darkMode] #darkBtn:after{content:"";right:-110px;top:8px;filter:invert(1) hue-rotate(180deg);font-weight:600;}#darkBtn:hover:after{display:block}#csdn-toolbar .toolbar-advert,#csdn-toolbar .toolbar-container-left,#csdn-toolbar .toolbar-container-right,.toolbar-search-drop-menu.toolbar-search-half,::-webkit-input-placeholder,#placeholder,#blogColumnPayAdvert,.csdn-side-toolbar,#dmp_ad_58,#footerRightAds,.csdn-shop-window-common,.login-mark,.blog-footer-bottom,.template-box,.leftPop,#toolBarBox,.comment-edit-box.d-flex,#passportbox,.opt-box.text-center,.hide-article-box.hide-article-pos.text-center,#rightAside,.hljs-button.signin{display:none !important;color:transparent;visibility:hidden}.toolbar-search.onlySearch{transition:all 0.3s ease;}body #csdn-toolbar{box-shadow:0 2px 10px 0 rgba(0,0,0,.15);position:fixed !important;top:0px;left:0px;width:100%;z-index:1993;}.toolbar-search.onlySearch:focus-within{max-width:1000px !important;width:1000px !important}.d-flex{display:block !important}.main_father{height:auto !important;}main{width:100% !important;box-shadow:0 0 30px #959fa378;margin-bottom:0 !important;}#mainBox{margin:50px auto;width:1000px !important}.comment-list-box{max-height:none !important}#commentPage,.toolbar-container-middle{display:block !important}#article_content{height:auto !important}.comment-list-container{padding:4px 0 !important}.article-header-box{padding-top:18px !important}main .comment-box{padding:0;box-shadow:0 0 10px rgba(0,0,0,0.05);margin:8px 0;}#FinnTop{width:36px;height:36px;color:#ff4d4d;font:600 14px/44px arial;text-align:center;position:fixed;left:60%;margin-left:520px;bottom:30px;z-index:999;cursor:pointer;background:#fff;border-radius:50%;box-shadow:0 0 20px #75757545;}#FinnTop:before{content:"";position:absolute;left:28%;top:36%;color:#ff4d4d;width:14px;height:14px;border-top:2px solid #ff4d4d;border-left:2px solid #ff4d4d;transform:rotate(45deg)}.blog_container_aside{height:calc(100% - 80px);overflow-y:auto;overflow-x:hidden;border:solid #fff;border-width:20px 4px 0 4px;background:#fff;box-sizing:content-box;position:fixed;top:initial !important;left:-307.8px !important;;transition:all 0.35s;box-shadow:2px 0 10px 0 rgba(0,0,0,.15);z-index:99;}.blog_container_aside::-webkit-scrollbar-track{-webkit-box-shadow:inset 0 0 15px rgba(0,0,0,0.13);background-color:#fefefe;}.blog_container_aside::-webkit-scrollbar{width:6px;height:6px;background-color:#eee;}.blog_container_aside::-webkit-scrollbar-thumb{border-radius:6px;background-color:#cecece;}.blog_container_aside:hover{left:0px !important;}.recommend-box.insert-baidu-box{height:79%;overflow:scroll;position:fixed;background:#fff;box-sizing:content-box;transition:all 0.38s;box-shadow:0 -3px 10px 0 rgba(0,0,0,.25);border:10px solid #fff;z-index:1995;top:calc(100% - 7px);left:0;right:0;margin:auto;width:1000px;}.recommend-box.insert-baidu-box:hover{top:29%}.recommend-box.insert-baidu-box::-webkit-scrollbar-thumb{background-color:rgba(153,154,170,0.3);}.recommend-box.insert-baidu-box::-webkit-scrollbar{width:5px;height:100px;}.recommend-item-box{display:none !important;}.recommend-item-box.type_blog{display:block !important;}/*aside.blog_container_aside:before{width:14px;animation:_l 1s ease-in forwards;position:fixed;top:58px;left:0;z-index:999;padding:5px 1px;background:#ff4d4d;text-align:center;color:#fff;content:" "attr(username) " "*/;writing-mode:tb-rl;font-size:12px;line-height:1.4;transition:all 0.35s ***@***.*** _l{from{left:-20px;}to{left:0;}}aside.blog_container_aside:hover::before{width:308px;height:18px;padding:4px 0;writing-mode:rl-tb;font-size:14px;}/*.recommend-box.insert-baidu-box:before{position:fixed;bottom:40px;left:50%;margin-left:510px;padding:4px;background:#ff4d4d;color:#fff;content:"推荐阅读"*/;font-size:13px}</style><div id="darkBtn"></div><div id="FinnTop"></div>`; const jb51 = `<style> #main .main-right,#topbar,#footer,.pt10,.lbd,.xgcomm,#header,.lbd_bot,#ewm,.subnav,.art_xg,.tags,#comments{display:none !important;}body #main .main-left{padding:0;width:unset;float:none}body #article{padding:15px 20px 20px;box-shadow:0 0 30px rgb(0 0 0 / 25%)}#ewm+p{font-weight:bold;text-align:center;margin:20px;font-size:24px;}body .syntaxhighlighter .line.alt1,body .syntaxhighlighter .line.alt2{background:#d4dbdc !important}body .syntaxhighlighter div{padding:10px 0px !important}.jb51code{width:960px !important}.jb51code .syntaxhighlighter table{background:#d4dbdc !important}</style>`; let h = document.documentElement, _Ds; let FinnData = new Proxy(GM_getValue('FinnData', {}), { set(target, key, val) { key === "dark" && val ? h.setAttribute("darkMode", true) : h.removeAttribute("darkMode"); Reflect.set(target, key, val); GM_setValue('FinnData', FinnData); return true; } }) if (location.host === "[www.jb51.net](http://www.jb51.net)") { _Ds = jb51; } else { _Ds = csdn; window.addEventListener("DOMContentLoaded", function () { document.querySelector(".blog_container_aside").setAttribute("username", username); document.body.addEventListener('click', function (e) { let ev = e.target; if (ev.nodeName.toLocaleLowerCase() === 'a') { if (ev.host.indexOf("csdn") === -1) { e.stopImmediatePropagation(); window.open(ev.href); e.preventDefault(); } } }, true); $("#FinnTop").click(function () { $("body,html").animate({ scrollTop: 0 }, 300); }); $("#darkBtn").click(function () { FinnData.dark ? FinnData.dark = !1 : FinnData.dark = !0; }) }) } if (!h) { let OB = new MutationObserver(ins); OB.observe(document, { childList: true }) } else { ins() } function ins() { h = document.documentElement; h.insertAdjacentHTML('afterbegin', _Ds); FinnData.dark && h.setAttribute("darkMode", true); } })();
> 

1.8 有调节内容尺寸的更新, 如果需要还是可以更新一下, 没有丑陋的红色按钮确实好看一些, 我改一下top按钮😂

**Comment by Germxu** [comment]
> 大大，搜索框是这个东西，就是这个白色长条，我想除了这个黄色圆圈和这个搜索框，剩下的白色背景能不能变透明，文章向下滚动时，最上面一直顶着个白色长条，看着不是很舒服

那是原本的顶部固定搜索栏, 现在还有搜索和调节按钮, 先留着吧, 可以自己改一下样式隐藏, 
搜索框也是我用不着的功能,留着只是协调一些, 那么大尺寸的框框悬浮的也挺不好看的
![t](https://user-images.githubusercontent.com/20300863/122532171-d2f37b80-d052-11eb-8752-f9578f88bcc0.png)

**Comment by ztf111** [comment]
大大，问个蠢问题，怎么改样式隐藏？我百度没搜到




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月18日(星期五) 下午4:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Germxu/Scripts-for-TamperMonkey] 大大，提几个建议 (#13)





  
大大，搜索框是这个东西，就是这个白色长条，我想除了这个黄色圆圈和这个搜索框，剩下的白色背景能不能变透明，文章向下滚动时，最上面一直顶着个白色长条，看着不是很舒服
  
那是原本的顶部固定搜索栏, 现在还有搜索和调节按钮, 先留着吧, 可以自己改一下样式隐藏,
 搜索框也是我用不着的功能,留着只是协调一些, 那么大尺寸的框框悬浮的也挺不好看的

**Comment by Germxu** [comment]
你改写CSS就可以了 , 如果不了解的话那就等先
body #csdn-toolbar {
只改头部白条的话找到这段加下面这行就行了
    background: transparent!important;
}

**Comment by ztf111** [comment]
嗯嗯好的，谢谢大大




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月18日(星期五) 下午4:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Germxu/Scripts-for-TamperMonkey] 大大，提几个建议 (#13)





 
你改写CSS就可以了 , 如果不了解的话那就等先
 body #csdn-toolbar {
 只改头部白条的话找到这段加下面这行就行了
 background: transparent!important;
 }

**Comment by Germxu** [comment]
更新1.9可以看下

**Comment by ztf111** [comment]
大大，要不直接把搜索框去掉吧，这玩意儿大部分人都用不到，学CSS自己改也是有点门槛的，我昨天研究了几个小时还是没搞明白怎么改




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月19日(星期六) 晚上11:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Germxu/Scripts-for-TamperMonkey] 大大，提几个建议 (#13)





 
更新1.9可以看下

**Comment by TarsChiu** [comment]
好家伙😂改不掉直接去😂😂😂(σ≧︎▽︎≦︎)σ。send

**Comment by ztf111** [comment]
大佬，我之前用了你改后的那个版本，然后文章背景就变成了星空动态图，特别好看！不造为啥，那个星空动态图隔一会儿就没了，变成了黑板背景，这是咋回事儿啊？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月20日(星期天) 上午9:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Germxu/Scripts-for-TamperMonkey] 大大，提几个建议 (#13)





 好家伙😂改不掉直接去😂😂😂(σ≧︎▽︎≦︎)σ。send

**Comment by TarsChiu** [comment]
其实我根本没动背景，只是单纯的top和左边和下面调了一下距离😂send

**Comment by ztf111** [comment]
可能那会儿我电脑出了神奇的bug，那个流动星空图是真好看，夜幕，群星流动，真好看，可惜这个bug一会儿就没了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月20日(星期天) 上午9:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Germxu/Scripts-for-TamperMonkey] 大大，提几个建议 (#13)





 其实我根本没动背景，只是单纯的top和左边和下面调了一下距离😂send

**Comment by Germxu** [comment]
背景都是文章的作者选的模板，不同的文章是不一样的，最新的1.9我干掉了，省的有人以为是我加的😶‍🌫️

**Comment by Germxu** [comment]
头部还是留着吧，我加东西也有的放，不为了有用，就为了协调
