### ISSUE TITLE
希望能把底部自动隐藏栏中显示的内容变成读者的评论

### ISSUE THREAD

**Issue by wrl2000** [Germxu/Scripts-for-TamperMonkey#17]
因为我个人觉得我们在阅读一篇csdn的时候更加关注的是已经读过的人的一些评论，而不是另外的一些推荐文章。往往我们可以根据一些别人发表的一些评论更好的判断一篇文章的好坏，如果不能够判断一篇文章的好坏再读十篇文章也没有用，所以希望，现在的插件中能够将推荐阅读和评论展示的位置更换一下，谢谢

**Comment by Germxu** [comment]
如果我没有看错的话我做的应该没有错？
推荐阅读是不显示的， 评论是展开并显示的

**Comment by wrl2000** [comment]
评论阅读希望能做成跟推荐阅读一样便捷显示，现在每篇文章需要拉倒最下面才能看到评论有点麻烦



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月7日(周日) 下午3:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Germxu/Scripts-for-TamperMonkey] 希望能把底部自动隐藏栏中显示的内容变成读者的评论 (Issue #17)




 
如果我没有看错的话我做的应该没有错？
 推荐阅读是不显示的， 评论是展开并显示的
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
