### ISSUE TITLE
CSDN Focus-bUG=

### ISSUE THREAD

**Issue by Benjaminzcq** [Germxu/Scripts-for-TamperMonkey#28]
【错误】
代码折叠部分不可见
【开启后】
![image](https://github.com/Germxu/Scripts-for-TamperMonkey/assets/66512071/777378b5-bf5f-4feb-a42f-c637392d20be)
【原来】
![image](https://github.com/Germxu/Scripts-for-TamperMonkey/assets/66512071/3aeb2ade-2912-4720-b5a9-39bc248d90d9)

**Comment by Germxu** [comment]
感谢反馈, 已经找到问题了, 等下就更新

**Comment by Germxu** [comment]
已发布更新, 可以手动更新到2.2.4
